### PR TITLE
Added DOM mouse and keyboard events

### PR DESCRIPTION
**Pull request by prust**
@syoyo: Instead of a global `onClick`, it's more typical in Javascript to define a global namespace and to support `addEventListener()`. I created a `bt3gui` namespace here, to expose the "mousebutton" event (and it shouldn't be hard to add "mousemove", "wheel" and "keyboard"). I'd also like to eventually expose the other bt3gui properties/methods (I think there's one to investigate if the Ctrl/Shift key is being pressed, etc).

The goal here is to expose a thin wrapper (bindings) around bt3gui that exposes everything bt3gui has to offer, and then to later write an HTML5 shim that maps the bt3gui API to the HTML5 API. 
(in the future, if someone were to create GLFW bindings, those could be done under a different `glfw` global and they could follow the same pattern with an HTML5 shim).

### CODE REVIEW

**Comment by servant-42** [comment]
@syoyo: In 7fa311a I added a shim that simulates the browser's `click`, `mousedown` and `mouseup` events. It's not perfect (the event still doesn't include the properties `altKey`, `ctrlKey`, `shiftKey` or `metaKey`), but it's a start.

**Comment by syoyo** [comment]
Thanks! It'd be better to wait the merge until you implement `altKey`, `ctrlKey`, etc? @prust

**Comment by servant-42** [comment]
@syoyo:

> better to wait

Yes, I think I'll have a chance to add those in soon.

**Comment by syoyo** [comment]
> Yes, I think I'll have a chance to add those in soon.

I see. Please let me know once you finished the implementation and ready to merge.

**Comment by servant-42** [comment]
@syoyo: Ok, this is ready to merge.

I added the modifier key properties for the mouse events and implemented the keyboard events (`keydown`, `keypress`, `keyup`). I did leave a few TODO comments in the code, but they would take a bit of research and I don't think they're important enough to hold up the merge.

I also implemented `bt3gui.setRequestExit()` and moved the escape-to-exit behavior from the main.cc to JS.

**Comment by syoyo** [comment]
Super cool! Merged.

**Pull request merged**
